 import React from "react";
import { useSellers } from "@/app/hooks/useFetchSellers";
import { useFetchPayments } from "@/app/hooks/useFetchPayments";
import type { Payment } from "@/app/utils/type";

export default function Metrics() {
  const { sellers } = useSellers();
  const { payments } = useFetchPayments();
  const total = sellers.length;
  const active = sellers.length; 
  const verified = sellers.length; 
  const revenue = payments.reduce((amount: number, payment: Payment) => amount + parseFloat(payment.amount), 0);

  return (
    <div className="flex gap-6 my-6">
      <div className="bg-white rounded-lg shadow p-4 flex-1 text-center">
        <h3 className="text-lg font-semibold text-[#5D070D]">Total Sellers</h3>
        <div className="text-3xl font-bold text-black">{total}</div>
        <div className="text-xs text-[#5D070D]">Registered artisans</div>
      </div>
      <div className="bg-white rounded-lg shadow p-4 flex-1 text-center">
        <h3 className="text-lg font-semibold text-[#5D070D]">Active Sellers</h3>
        <div className="text-3xl font-bold text-black">{active}</div>
        <div className="text-xs text-[#5D070D]">Currently active</div>
      </div>
      <div className="bg-white rounded-lg shadow p-4 flex-1 text-center">
        <h3 className="text-lg font-semibold text-[#5D070D]">Verified Sellers</h3>
        <div className="text-3xl font-bold text-black">{verified}</div>
        <div className="text-xs text-[#5D070D]">Identity confirmed</div>
      </div>
      <div className="bg-white rounded-lg shadow p-4 flex-1 text-center">
        <h3 className="text-lg font-semibold text-[#5D070D]">Total Revenue</h3>
        <div className="text-3xl font-bold text-black">KSh {revenue.toLocaleString()}</div>
        <div className="text-xs text-[#5D070D]">Generated by sellers</div>
      </div>
    </div>
  );
} 