 import React from "react";
import { useSellers } from "@/app/hooks/useFetchSellers";
import { useFetchPayments } from "@/app/hooks/useFetchPayments";
import type { Payment } from "@/app/utils/type";

export default function Metrics() {
  const { sellers } = useSellers();
  const { payments } = useFetchPayments();
  const total = sellers.length;
  const active = sellers.length; 
  const verified = sellers.length; 
  const revenue = payments.reduce((amount: number, payment: Payment) => amount + parseFloat(payment.amount), 0);

  return (
    <div className="flex gap-6 my-6">
      <div className="bg-white [@media(width:1024)]:h-26 rounded-lg shadow p-4 flex-1 text-center xl:h-20">
        <h3 className="text-lg [@media(width:1024)]:text-sm font-semibold text-[#5D070D] xl:text-[15px]">Total Sellers</h3>
        <div className="text-3xl [@media(width:1024)]:text-2xl font-bold text-black xl:text-[18px]">{total}</div>
        <div className="text-xs text-[#5D070D]">Registered artisans</div>
      </div>
      <div className="bg-white [@media(width:1024)]:h-26  rounded-lg shadow p-4 flex-1 text-center xl:h-20">
        <h3 className="text-lg [@media(width:1024)]:text-sm font-semibold text-[#5D070D] xl:text-[15px]">Active Sellers</h3>
        <div className="text-3xl [@media(width:1024)]:text-2xl  font-bold text-black xl:text-[18px]">{active}</div>
        <div className="text-xs text-[#5D070D]">Currently active</div>
      </div>
      <div className="bg-white [@media(width:1024)]:h-26  rounded-lg shadow p-4 flex-1 text-center xl:h-20">
        <h3 className="text-lg [@media(width:1024)]:text-sm font-semibold text-[#5D070D] xl:text-[15px]">Verified Sellers</h3>
        <div className="text-3xl [@media(width:1024)]:text-2xl  font-bold text-black xl:text-[18px]">{verified}</div>
        <div className="text-xs text-[#5D070D]">Identity confirmed</div>
      </div>
      <div className="bg-white [@media(width:1024)]:h-26  rounded-lg shadow p-4 flex-1 text-center xl:h-20">
        <h3 className="text-lg [@media(width:1024)]:text-sm font-semibold text-[#5D070D] xl:text-[15px]">Total Revenue</h3>
        <div className="text-3xl [@media(width:1024)]:text-2xl font-bold text-black xl:text-[18px]">Ksh {revenue.toLocaleString()}</div>
        <div className="text-xs text-[#5D070D]">Generated by sellers</div>
      </div>
    </div>
  );
} 